version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: sempdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin321
    ports:
      - 9966:5432