server:
  port: 9000
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:9966/semp
    username: admin
    password: admin321
  jpa:
    hibernate:
      ddl-auto: validate